<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    { 
        DB::table('users')->delete();

        $data = [
            [
                'user_id' => "EMP-001",
                'name' => "Super Admin",
                'phone' => "01700000000",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1,
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-002",
                'name' => "General Manager",
                'phone' => "01700000001",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-003",
                'name' => "Deputy General Manager",
                'phone' => "01700000002",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1,
                
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-004",
                'name' => "Assistant General Manager",
                'phone' => "01700000003",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1,
                
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-005",
                'name' => "Sales Manager",
                'phone' => "01700000004",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1,
                
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-006",
                'name' => "Regional Manager",
                'phone' => "01700000005",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1,
                
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-007",
                'name' => "Zonal Co-Ordinator",
                'phone' => "01700000006",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1,
                
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ]
            ,[
                'user_id' => "EMP-008",
                'name' => "Senior Zonal Manager",
                'phone' => "01700000007",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1,
                
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-009",
                'name' => "Zonal Manager",
                'phone' => "01700000008",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1,
                
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ]
            ,[
                'user_id' => "EMP-010",
                'name' => "Asst. Zonal Manager",
                'phone' => "01700000009",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1,
                
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ]
            ,[
                'user_id' => "EMP-011",
                'name' => "Area Incharge",
                'phone' => "01700000010",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ]
            ,[
                'user_id' => "EMP-012",
                'name' => "DSM",
                'phone' => "01700000011",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ]
            ,[
                'user_id' => "EMP-013",
                'name' => "ASM",
                'phone' => "01700000012",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-014",
                'name' => "Sr. Executive",
                'phone' => "01700000013",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-015",
                'name' => "Sales Executive",
                'phone' => "01700000014",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-016",
                'name' => "Junior Executive",
                'phone' => "01700000015",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "EMP-017",
                'name' => "Excutive Marketing",
                'phone' => "01700000016",
                'password' => bcrypt('123456'),
                'user_type' => 1,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "FL-001",
                'name' => "Ex.Co-Ordinator",
                'phone' => "01700000017",
                'password' => bcrypt('123456'),
                'user_type' => 2,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "FL-002",
                'name' => "Co Ordinator",
                'phone' => "01700000018",
                'password' => bcrypt('123456'),
                'user_type' => 2,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "FL-003",
                'name' => "Co-Ordinator Applicant",
                'phone' => "01700000019",
                'password' => bcrypt('123456'),
                'user_type' => 2,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ],[
                'user_id' => "FL-004",
                'name' => "Franchise Partner",
                'phone' => "01700000020",
                'password' => bcrypt('123456'),
                'user_type' => 2,
                'profile_image' => "",
                'marital_status' => 1, 
                'finger_id' => "43435343",
                'region' => 1,
                'blood_group' => 1,
                'gender' => 1, 
                'created_by' => 1, 
                'updated_by' => 1,
            ]
        ];
        DB::table('users')->insert($data); 

        $freelancer_data = [
            [
                'user_id' => 18,
                'profession_id' => 1,
                'designation_id' => 21, 
                'last_approve_by' => 17,
            ],
            [
                'user_id' => 19,
                'profession_id' => 1,
                'designation_id' => 21, 
                'last_approve_by' => 17,
            ],
            [
                'user_id' => 20,
                'profession_id' => 1,
                'designation_id' => 21,
                'last_approve_by' => 17, 
            ],

            [
                'user_id' => 21,
                'profession_id' => 1,
                'designation_id' => 21, 
                'last_approve_by' => 17,
            ],
        ]; 
        DB::table('freelancers')->insert($freelancer_data);
    }
}
